---
defaults: &defaults

development:
  <<: *defaults
  game_handler: GameMachine::Handler::Request
  data_store: couchbase
  couchbase_servers: 
    - http://127.0.0.1:8091/pools
  write_behind_cache:
    write_interval: 10000
    max_writes_per_second: 10
  login_username: 'player'
  login_password: 'pass'
  authtoken: 'authorized'
  http_host: localhost
  http_port: 8080
  seeds:
    - seed01
    - seed02
  servers:
    default:
      http_enabled: false
      udp:
        port: 8100
        host: localhost
        enabled: true
      udt:
        port: 8200
        host: localhost
        enabled: true
      akka:
        host: localhost
        port: 2551
    seed01:
      http_enabled: true
      udp:
        port: 8100
        host: localhost
        enabled: true
      udt:
        port: 8200
        host: localhost
        enabled: true
      akka:
        host: localhost
        port: 2552
    seed02:
      http_enabled: false
      udp:
        port: 8101
        host: localhost
        enabled: true
      udt:
        port: 8201
        host: localhost
        enabled: false
      akka:
        host: localhost
        port: 2553
    member01:
      http_enabled: false
      udp:
        port: 8102
        host: localhost
        enabled: true
      udt:
        port: 8202
        host: localhost
        enabled: true
      akka:
        host: localhost
        port: 0
    member02:
      http_enabled: false
      udp:
        port: 8103
        host: localhost
        enabled: true
      udt:
        port: 8203
        host: localhost
        enabled: true
      akka:
        host: localhost
        port: 0

test:
  <<: *defaults
  game_handler: GameMachine::Handler::Request
  login_username: 'player'
  login_password: 'pass'
  authtoken: 'authorized'
  http_host: localhost
  http_port: 8080
  data_store: memory
  write_behind_cache:
    write_interval: 10000
    max_writes_per_second: 10
  seeds:
    - default
  servers:
    default:
      http_enabled: false
      udp:
        port: 8100
        host: localhost
        enabled: true
      udt:
        port: 8200
        host: localhost
        enabled: false
      akka:
        host: localhost
        port: 2551

production:
  <<: *defaults
