---
development:
  servers:
    default:
      environment: development
      use_regions: true
      team_handler: GameMachine::DefaultHandlers::TeamHandler
      # Authorization handler.  Public allows any authtoken to be used and
      # does not check username/password
      #auth_handler: GameMachine::DefaultHandlers::Authentication::ObjectStore
      auth_handler: GameMachine::AuthHandlers::Public
      # Class that handles user registration via web page
      player_register_handler: GameMachine::DefaultHandlers::Authentication::PlayerRegister
      #player_register_handler: Example::PlayerRegister
      # Size of the router for incoming message from all clients
      game_handler_routers: 20
      # Also in the pipeline for all incoming requests, should be set the same as
      # game_handler_routers
      request_handler_routers: 20
      # router size for the udp actor that handles all incoming upd messages
      udp_routers: 10
      # What data store the object database will use (one of memory, mapdb, or couchbase)
      data_store: memory
      # minimum time in milliseconds between writes to the backing store of the same key.  When a message
      # exceeds the limit it is either enqueued, or if already enqueued, it's value is updated, it's
      # value is updated. -1 disables caching.  Default 1000
      cache_write_interval: -1
      # Total writes per second to the backing store that an actor will allow, across all keys.  Note this is on a per actor
      # basis.  If you want to limit total writes per second to your database, this value should be a multiple of the number
      # of write behind cache actors that are started.  -1 disables caching. Default 100
      cache_writes_per_second: -1
      # Spatial grids.  default, aoe, and local_chat are required.
      # value is grid size, cell size, and update frequency
      grids:
        default: 4000, 50, 1
        aoe: 4000, 5, 1
        local_chat: 4000, 10, 10
      orm: false
      # JDBC
      #
      # Mysql
      jdbc_hostname: 127.0.0.1
      jdbc_database: game_machine
      jdbc_url: jdbc:mysql://127.0.0.1:3306/game_machine
      jdbc_driver: com.mysql.jdbc.Driver
      jdbc_username: root
      jdbc_password: mysql
      # Couchbase config
      couchbase_bucket: gamemachine
      couchbase_password: pass
      couchbase_servers:
        - http://127.0.0.1:8091/pools
      http_enabled: true
      http_host: 0.0.0.0
      http_port: 3000
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 24130
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8910
      akka_host: 0.0.0.0
      akka_port: 2551
      # array of seed servers.  Required if node is in a cluster
      seeds: [default]
      # Mono server settings
      mono_enabled: false