---
development:
  id: 1
  mono_enabled: false
  environment: development
  game_handler: GameMachine::Handlers::Request
  data_store: memory
  couchbase_servers: http://217.0.0.1:8091/pools
  cache_write_interval: -1
  cache_writes_per_second: -1
  world_grid_size: 2000
  world_grid_cell_size: 25
  singleton_manager_router_count: 200
  singleton_manager_update_interval: 100
  seeds:
  - seed01
  - seed02
  auth_handler: GameMachine::AuthHandlers::Basic
  servers:
    default:
      id: 1
      environment: development
      name: default
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: true
      udt_host: localhost
      udt_port: 8200
      akka_host: localhost
      akka_port: 2551
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
    seed01:
      id: 2
      environment: development
      name: seed01
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: true
      udt_host: localhost
      udt_port: 8200
      akka_host: localhost
      akka_port: 2552
      status: 0
      enabled: true
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
    seed02:
      id: 3
      environment: development
      name: seed02
      http_enabled: false
      http_host: localhost
      http_port: 8080
      udp_enabled: false
      udp_host: 0.0.0.0
      udp_port: 8101
      udt_enabled: false
      udt_host: localhost
      udt_port: 8201
      akka_host: localhost
      akka_port: 2553
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
    member01:
      id: 4
      environment: development
      name: member01
      http_enabled: false
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8102
      udt_enabled: false
      udt_host: localhost
      udt_port: 8202
      akka_host: localhost
      akka_port: 0
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
production:
  id: 2
  mono_enabled: false
  environment: production
  game_handler: GameMachine::Handlers::Request
  data_store: couchbase
  couchbase_servers: http://217.0.0.1:8091/pools
  cache_write_interval: 10
  cache_writes_per_second: 100
  world_grid_size: 2000
  world_grid_cell_size: 25
  singleton_manager_router_count: 200
  singleton_manager_update_interval: 100
  seeds:
  - seed01
  - seed02
  auth_handler: GameMachine::AuthHandlers::Basic
  servers: {}
test:
  id: 3
  mono_enabled: false
  environment: test
  game_handler: GameMachine::Handlers::Request
  data_store: memory
  couchbase_servers: http://217.0.0.1:8091/pools
  cache_write_interval: -1
  cache_writes_per_second: -1
  world_grid_size: 2000
  world_grid_cell_size: 25
  singleton_manager_router_count: 200
  singleton_manager_update_interval: 100
  seeds:
  - seed01
  - seed02
  auth_handler: GameMachine::AuthHandlers::Basic
  servers:
    default:
      id: 5
      environment: test
      name: default
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: true
      udt_host: localhost
      udt_port: 8200
      akka_host: localhost
      akka_port: 2551
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
    seed01:
      id: 6
      environment: test
      name: seed01
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: true
      udt_host: localhost
      udt_port: 8200
      akka_host: localhost
      akka_port: 2552
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
    seed02:
      id: 7
      environment: test
      name: seed02
      http_enabled: false
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8101
      udt_enabled: true
      udt_host: localhost
      udt_port: 8201
      akka_host: localhost
      akka_port: 2553
      status: 0
      enabled: false
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
