---
development:
  servers:
    default:
      environment: development
      # Handles requests for matchmaking and custom filtering for teams.
      # If no team handler is defined defaults are used
      team_handler: Plugins::TeamHandler
      # Authorization handler.  Public allows any authtoken to be used and
      # does not check username/password
      auth_handler: Example::AuthenticationHandler
      #auth_handler: GameMachine::AuthHandlers::Public
      # Class that handles user registration via web page
      player_register_handler: Example::PlayerRegister
      # Player manager.  Receives player status updates
      player_manager: Example::PlayerManager
      # Top level actor that handles game messages. Don't change this 
      game_handler: GameMachine::Handlers::Request
      # Hook for accessing location updates from players (cheat prevention)
      entity_tracking_handler: Example::TrackingHandler
      # Size of the router for incoming message from all clients
      game_handler_routers: 10
      # Also in the pipeline for all incoming requests, should be set the same as
      # game_handler_routers
      request_handler_routers: 10
      # router size for the udp actor that handles all incoming upd messages
      udp_routers: 10
      # What data store the object database will use (one of memory, mapdb, or couchbase)
      data_store: mapdb
      # Advanced settings for write behind cache.  -1 disables.  This is fine for
      # all but large games with high traffic (hundreds of writes per second)
      cache_write_interval: -1
      cache_writes_per_second: -1
      # Spatial grids.  default, aoe, and local_chat are required.
      # value is grid size, cell size, and update frequency
      grids:
        default: 4000, 50, 1
        aoe: 4000, 5, 1
        local_chat: 4000, 10, 10
      # Mysql config
      mysql_url: jdbc:mysql://localhost:3306/game_machine
      mysql_driver: com.mysql.jdbc.Driver
      mysql_username: root
      mysql_password:
      # Couchbase config
      couchbase_bucket: default
      couchbase_password:
      couchbase_servers:
        - http://127.0.0.1:8091/pools
      http_enabled: true
      http_host: 0.0.0.0
      http_port: 3000
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 24130
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: 127.0.0.1
      akka_port: 2551
      # array of seed servers.  Required if node is in a cluster
      seeds: [default,seed01]
      # Mono server settings
      mono_enabled: false
    seed01:
      environment: development
      team_handler: Plugins::TeamHandler
      auth_handler: Example::AuthenticationHandler
      player_register_handler: Example::PlayerRegister
      player_manager: Example::PlayerManager
      game_handler: GameMachine::Handlers::Request
      entity_tracking_handler: Example::TrackingHandler
      game_handler_routers: 10
      request_handler_routers: 10
      udp_routers: 10
      data_store: mapdb
      cache_write_interval: -1
      cache_writes_per_second: -1
      grids:
        default: 4000, 50, 1
        aoe: 4000, 5, 1
        local_chat: 4000, 10, 10
      mysql_url: jdbc:mysql://localhost:3306/game_machine
      mysql_driver: com.mysql.jdbc.Driver
      mysql_username: root
      mysql_password:
      couchbase_bucket: default
      couchbase_password:
      couchbase_servers:
        - http://127.0.0.1:8091/pools
      http_enabled: false
      http_host: 127.0.0.1
      http_port: 3000
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 24130
      tcp_enabled: false
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: 127.0.0.1
      akka_port: 2551
      seeds: [default,seed01]
      mono_enabled: false
