---
development:
  servers:
    default:
      id: 1
      user_id: 1
      cluster_id: 1
      environment: development
      game_handler: GameMachine::Handlers::Request
      data_store: memory
      cache_write_interval: -1
      cache_writes_per_second: -1
      world_grid_size: 2000
      world_grid_cell_size: 25
      mono_enabled: false
      mono_dll: test_actor.dll
      singleton_manager_router_count: 200
      singleton_manager_update_interval: 100
      couchbase_servers: http://217.0.0.1:8091/pools
      auth_handler: GameMachine::AuthHandlers::Basic
      http_enabled: true
      http_host: 0.0.0.0
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: false
      udt_host: localhost
      udt_port: 8200
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2551
      created_at: 2013-11-10 05:38:50.000000000 Z
      updated_at: 2013-11-10 05:38:50.000000000 Z
      seeds: []
      message_gateway_host: 0.0.0.0
      message_gateway_port: 8800
    seed01:
      id: 2
      user_id: 1
      cluster_id: 1
      environment: development
      game_handler: GameMachine::Handlers::Request
      data_store: memory
      cache_write_interval: -1
      cache_writes_per_second: -1
      world_grid_size: 2000
      world_grid_cell_size: 25
      mono_enabled: true
      singleton_manager_router_count: 200
      singleton_manager_update_interval: 100
      couchbase_servers: http://217.0.0.1:8091/pools
      auth_handler: GameMachine::AuthHandlers::Basic
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: true
      udt_host: localhost
      udt_port: 8200
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2552
      created_at: 2013-11-10 05:38:50.000000000 Z
      updated_at: 2013-11-10 05:38:50.000000000 Z
      seeds: []
    seed02:
      id: 3
      user_id: 1
      cluster_id: 1
      environment: development
      game_handler: GameMachine::Handlers::Request
      data_store: memory
      cache_write_interval: -1
      cache_writes_per_second: -1
      world_grid_size: 2000
      world_grid_cell_size: 25
      mono_enabled: true
      singleton_manager_router_count: 200
      singleton_manager_update_interval: 100
      couchbase_servers: http://217.0.0.1:8091/pools
      auth_handler: GameMachine::AuthHandlers::Basic
      http_enabled: false
      http_host: localhost
      http_port: 8080
      udp_enabled: false
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: false
      udt_host: localhost
      udt_port: 8200
      tcp_enabled: false
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2553
      created_at: 2013-11-10 05:38:50.000000000 Z
      updated_at: 2013-11-10 05:38:50.000000000 Z
      seeds: []
test:
  servers:
    default:
      id: 4
      user_id: 1
      cluster_id: 2
      environment: test
      game_handler: GameMachine::Handlers::Request
      data_store: memory
      cache_write_interval: -1
      cache_writes_per_second: -1
      world_grid_size: 2000
      world_grid_cell_size: 25
      mono_enabled: true
      mono_dll: test_actor.dll
      singleton_manager_router_count: 200
      singleton_manager_update_interval: 100
      couchbase_servers: http://217.0.0.1:8091/pools
      auth_handler: GameMachine::AuthHandlers::Basic
      http_enabled: true
      http_host: localhost
      http_port: 8080
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: false
      udt_host: localhost
      udt_port: 8200
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2551
      created_at: 2013-11-10 05:38:50.000000000 Z
      updated_at: 2013-11-10 05:38:50.000000000 Z
      seeds: []
      message_gateway_host: 0.0.0.0
      message_gateway_port: 8800
