development:
  servers:
    default:
      environment: development
      player_register_handler: Example::PlayerRegister
      game_handler: GameMachine::Handlers::Request
      entity_tracking_handler: Example::TrackingHandler
      game_handler_routers: 5
      request_handler_routers: 5
      udp_routers: 5
      data_store: mapdb
      cache_write_interval: -1
      cache_writes_per_second: -1
      grids:
        default: 4000, 50, 1
        aoe: 4000, 5, 1
        local_chat: 4000, 10, 10
      couchbase_servers:
        - http://127.0.0.1:8091/pools
      auth_handler: Example::AuthenticationHandler
      http_enabled: true
      http_host: 127.0.0.1
      http_port: 3000
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      udt_enabled: false
      udt_host: localhost
      udt_port: 8200
      tcp_enabled: false
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2551
      seeds: []
      mono_enabled: false
      mono_dll: test_actor.dll
      mono_gateway_host: 127.0.0.1
      mono_gateway_port: 8800
