---
development:
  protogen_out_dir: /tmp
  servers:
    default:
      id: 1
      user_id: 1
      cluster_id: 1
      environment: development
      game_handler: GameMachine::Handlers::Request
      data_store: memory
      cache_write_interval: -1
      cache_writes_per_second: -1
      world_grid_size: 2000
      world_grid_cell_size: 25
      mono_enabled: false
      singleton_manager_router_count: 200
      singleton_manager_update_interval: 100
      couchbase_servers: http://217.0.0.1:8091/pools
      auth_handler: GameMachine::AuthHandlers::Basic
      http_enabled: true
      http_host: 0.0.0.0
      http_port: 3000
      udp_enabled: true
      udp_host: 0.0.0.0
      udp_port: 8100
      tcp_enabled: true
      tcp_host: 0.0.0.0
      tcp_port: 8700
      akka_host: localhost
      akka_port: 2551
      seeds: []
      mono_gateway_host: 127.0.0.1
      mono_gateway_port: 8800
