---
:game_users:
- id: 1
  user: test_user
  pass: test_pass
  roles:
  auth_token:
- id: 2
  user: player
  pass: pass
  roles:
  auth_token: authorized
:entities: []
:components:
  :effects: []
  :attacks: []
  :combat_abilities: []
:assets: []
