---
development:
  regions:
    zone1: Example::ZoneManager
    zone2: Example::ZoneManager
test:
  regions:
    zone1: GameMachine::GameSystems::Zone1Manager
    zone2: GameMachine::GameSystems::Zone2Manager
