---
defaults: &defaults

development:
  <<: *defaults
  game_handler: GameMachine::CommandRouter
  message_encoding: protobuf
  servers:
    default:
      udp:
        port: 8100
        host: localhost
        enabled: false
        log_level: INFO
      udt:
        port: 8101
        host: localhost
        enabled: false
        log_level: INFO
      akka:
        host: localhost
        port: 2552
    seed1:
      udp:
        port: 8100
        host: localhost
        enabled: false
        log_level: INFO
      udt:
        port: 8101
        host: localhost
        enabled: true
        log_level: INFO
      akka:
        host: localhost
        port: 2551
    app01:
      udp:
        port: 8100
        host: localhost
        enabled: false
        log_level: INFO
      udt:
        port: 8101
        host: localhost
        enabled: true
        log_level: INFO
      akka:
        host: localhost
        port: 2553

test:
  <<: *defaults
  game_handler: GameMachine::CommandRouter
  message_encoding: protobuf
  servers:
    default:
      udp:
        port: 8100
        host: 192.168.1.2
        enabled: true
        log_level: INFO
      udt:
        port: 8101
        host: 192.168.1.2
        enabled: true
        log_level: INFO
      akka:
        host: localhost
        port: 2552
    app01:
      udp:
        port: 8100
        host: localhost
        enabled: false
        log_level: INFO
      udt:
        port: 8101
        host: localhost
        enabled: false
        log_level: INFO
      akka:
        host: localhost
        port: 2553

production:
  <<: *defaults
